// Data parser
// For data generated by OBD fusion app
// https://www.obdsoftware.net/software/obdfusion


// Load Data file via http://papaparse.com/
var Papa = require('papaparse')


// Papa parse file
var papaFile = function(input, callback) {
    // if file selected
    if (input.files.length > 0) {

    	//var status = document.querySelector('.chrom-stats')
		//status.innerHTML = "Loading Data..."

        Papa.parse(input.files[0], {
            delimiter: "", // auto-detect
            newline: "", // auto-detect
            quoteChar: '"',
            comments: "#",
            header: true,
            skipEmptyLines: true,
            error: function(err, file, inputElem, reason) {
                console.log("File loading error:", err, reason)
                callback( null )
            },
            complete: function(results) {
                console.log("File loaded: ", results);
               	callback( results )
            }
        })
    }


}

// Map parsed results to array useable for viz
var parseDatafile = function(rawData) {

	// if error 
	if(rawData === null){
		return (null)
	}


    return (rawData)

}


// export
module.exports = {
	papaFile: papaFile,
	parseDatafile: parseDatafile
}


